# Generated by Django 5.1.4 on 2025-02-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_tag_articleimage_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Juan Perez', max_length=200)),
                ('email', models.EmailField(default='Correo electrónico', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='title',
            field=models.CharField(default='Titulo', max_length=200),
        ),
    ]
