# Generated by Django 5.1.4 on 2025-05-20 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_resena_rating_alter_resena_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='content.ciudad'),
        ),
    ]
