# Generated by Django 5.1.4 on 2025-02-21 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_article_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleImage',
            new_name='Imagen',
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='Resena',
        ),
        migrations.RenameField(
            model_name='imagen',
            old_name='ciudad',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='resena',
            old_name='ciudad',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='po',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='title',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='email',
        ),
        migrations.AddField(
            model_name='ciudad',
            name='categories',
            field=models.ManyToManyField(related_name='ciudades', to='content.categoria'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='name',
            field=models.CharField(default='Nombre', max_length=200),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='province',
            field=models.ForeignKey(default='Castilla la Mancha', on_delete=django.db.models.deletion.CASCADE, to='content.provincia'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='text',
            field=models.TextField(default='Texto'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='name',
            field=models.CharField(default='Castilla la Mancha', max_length=200),
        ),
    ]
